#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Mon Jul 23 11:10:03 2018

@author: greg
"""
class ePuck:
    
    clientID = 0
    
    def __init__(self, handle):
        self.h  = handle
        
    def set_pos(position: '[x y z] metres'):
        
        # Set position
        returnCode = vrep.simxSetObjectPosition(
                clientID, self.h, -1, position, vrep.simx_opmode_oneshot)
        
